name: WebGoat # workflow name 
on:
 push:
   branches: 
     - main
jobs:
 build:
   runs-on: ubuntu-latest 
   steps:
     - run: echo "This is a build step"  

 test:
   runs-on: ubuntu-latest
   steps: 
     - run: echo "This is a test step"

 secret_scanning:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2

      - run: docker run --rm -v $(pwd):/src trufflesecurity/trufflehog file:///src --json > trufflehog-output.json
        continue-on-error: true             # allow the build to fail

      - uses: actions/upload-artifact@v2
        with:
          name: TruffleHog
          path: trufflehog-output.json
        if: always()

 integration:
   runs-on: ubuntu-latest
   steps:
     - run: echo "This is an integration step"
     - run: exit 1

 prod:
   runs-on: ubuntu-latest
   steps:
 - run: echo "This is a deploy step" 
